//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Management_System.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUser
    {
        public int ProjectUserID { get; set; }
        public int ProjectID { get; set; }
        public int UserID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Userinfo Userinfo { get; set; }
    }
}
