//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Management_System.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDocumentation
    {
        public int ProjectDocumentationID { get; set; }
        public string ProjectID { get; set; }
        public string ProjectDocumentationAttachment { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
